### ISSUE TITLE
Bug server-side data

### ISSUE THREAD

**Issue by dcorb** [jaydenseric/graphql-react-examples#7]
Server-side query is not loading data for me.
I can't locate the bug, sorry for the vague description of the bug

To replicate, clone https://github.com/jaydenseric/graphql-react-examples
run `npm install graphql-react@latest` 
this will upgrade from v16 to v17
and it will break the ssr data
`cacheValue` will be always undefined.

**Comment by jaydenseric** [comment]
This project has now been changed from a Node.js and Next.js app deployed with Vercel, to a [Deno](https://deno.land) and [Ruck](https://ruck.tech) based app deployed with [Fly.io](https://fly.io):

https://graphql-react-examples.fly.dev

The new project IMO is simpler and easier to reason about, and because it's likely any old problems don't apply to the new setup I'm closing this issue. That said, feel free to comment if you figure out what your original problem was.
